"""mod project, work

Revision ID: 586224e97f73
Revises: fb71981de880
Create Date: 2024-11-09 09:42:46.769555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586224e97f73'
down_revision: Union[str, None] = 'fb71981de880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_period', sa.String(length=10), nullable=False, comment='開始日 (YYYY/MM/DD)'))
    op.add_column('projects', sa.Column('end_period', sa.String(length=10), nullable=False, comment='終了日 (YYYY/MM/DD)'))
    op.add_column('projects', sa.Column('order', sa.Integer(), nullable=False, comment='表示順'))
    op.add_column('projects', sa.Column('is_pickup', sa.Boolean(), nullable=False, comment='ピックアップフラグ'))
    op.drop_column('projects', 'url')
    op.drop_column('projects', 'image_path')
    op.add_column('works', sa.Column('is_pickup', sa.Boolean(), nullable=False, comment='ピックアップフラグ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'is_pickup')
    op.add_column('projects', sa.Column('image_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='画像パス'))
    op.add_column('projects', sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='URL'))
    op.drop_column('projects', 'is_pickup')
    op.drop_column('projects', 'order')
    op.drop_column('projects', 'end_period')
    op.drop_column('projects', 'start_period')
    # ### end Alembic commands ###
