"""add column skill(order)

Revision ID: 9aab506e7e31
Revises: a8b7eb2a60e0
Create Date: 2024-11-10 13:03:30.724829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aab506e7e31'
down_revision: Union[str, None] = 'a8b7eb2a60e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('order', sa.Integer(), nullable=False, comment='表示順'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'order')
    # ### end Alembic commands ###
