"""restore project(image_path, url)

Revision ID: b70cb28c1c8c
Revises: 586224e97f73
Create Date: 2024-11-09 09:58:43.334333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70cb28c1c8c'
down_revision: Union[str, None] = '586224e97f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_path', sa.String(length=200), nullable=True, comment='画像パス'))
    op.add_column('projects', sa.Column('url', sa.String(length=200), nullable=True, comment='URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'url')
    op.drop_column('projects', 'image_path')
    # ### end Alembic commands ###
