"""create table

Revision ID: fb71981de880
Revises: 
Create Date: 2024-11-07 21:25:37.066140

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import models

# revision identifiers, used by Alembic.
revision: str = "fb71981de880"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_eras",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "title",
            sa.String(length=100),
            nullable=False,
            comment="時代区分名",
        ),
        sa.Column(
            "start_period", sa.Integer(), nullable=True, comment="開始期間"
        ),
        sa.Column(
            "end_period", sa.Integer(), nullable=True, comment="終了期間"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="説明"),
        sa.Column("order", sa.Integer(), nullable=False, comment="表示順"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "levels",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "level",
            sa.String(length=100),
            nullable=False,
            comment="レベル表記",
        ),
        sa.Column(
            "description",
            sa.String(length=100),
            nullable=False,
            comment="レベル感の説明",
        ),
        sa.Column("order", sa.Integer(), nullable=False, comment="表示順"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processes",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "name", sa.String(length=50), nullable=False, comment="工程名"
        ),
        sa.Column(
            "description", sa.String(length=200), nullable=True, comment="説明"
        ),
        sa.Column("order", sa.Integer(), nullable=False, comment="表示順"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profiles",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="名前"
        ),
        sa.Column(
            "image_path",
            sa.String(length=200),
            nullable=True,
            comment="プロフィール画像パス",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="自己紹介"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="タイトル"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="説明"),
        sa.Column(
            "image_path",
            sa.String(length=200),
            nullable=True,
            comment="画像パス",
        ),
        sa.Column("url", sa.String(length=200), nullable=True, comment="URL"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill_categories",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "code",
            sa.String(length=20),
            nullable=False,
            comment="カテゴリコード",
        ),
        sa.Column(
            "name", sa.String(length=50), nullable=False, comment="カテゴリ名"
        ),
        sa.Column(
            "description", sa.String(length=200), nullable=True, comment="説明"
        ),
        sa.Column("order", sa.Integer(), nullable=False, comment="表示順"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "technology_categories",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "name", sa.String(length=50), nullable=False, comment="カテゴリ名"
        ),
        sa.Column(
            "description", sa.String(length=200), nullable=True, comment="説明"
        ),
        sa.Column("order", sa.Integer(), nullable=False, comment="表示順"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "works",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="タイトル"
        ),
        sa.Column(
            "start_period",
            sa.String(length=7),
            nullable=False,
            comment="開始日 (YYYY/MM)",
        ),
        sa.Column(
            "end_period",
            sa.String(length=7),
            nullable=False,
            comment="終了日 (YYYY/MM)",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="説明"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "background_events",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "era_id", sa.Integer(), nullable=False, comment="時代区分ID"
        ),
        sa.Column(
            "start_period", sa.Integer(), nullable=True, comment="開始期間"
        ),
        sa.Column(
            "end_period", sa.Integer(), nullable=True, comment="終了期間"
        ),
        sa.Column(
            "is_single",
            sa.Boolean(),
            nullable=True,
            comment="単一期間フラグ（期間の範囲表示に~を使用するか）",
        ),
        sa.Column("description", sa.Text(), nullable=False, comment="説明"),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["era_id"],
            ["background_eras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "technologies",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "name", sa.String(length=50), nullable=False, comment="技術名"
        ),
        sa.Column(
            "category_id", sa.Integer(), nullable=False, comment="カテゴリID"
        ),
        sa.Column(
            "description", sa.String(length=200), nullable=True, comment="説明"
        ),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["technology_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_processes",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column("work_id", sa.Integer(), nullable=False, comment="業務ID"),
        sa.Column(
            "process_id", sa.Integer(), nullable=False, comment="工程ID"
        ),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_technologies",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
            comment="プロジェクトID",
        ),
        sa.Column(
            "technology_id", sa.Integer(), nullable=False, comment="技術ID"
        ),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "technology_id", sa.Integer(), nullable=False, comment="技術ID"
        ),
        sa.Column(
            "level_id", sa.Integer(), nullable=False, comment="レベルID"
        ),
        sa.Column(
            "category_id", sa.Integer(), nullable=False, comment="カテゴリID"
        ),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["skill_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_technologies",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column("work_id", sa.Integer(), nullable=False, comment="業務ID"),
        sa.Column(
            "technology_id", sa.Integer(), nullable=False, comment="技術ID"
        ),
        sa.Column(
            "apply_start_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用開始日時",
        ),
        sa.Column(
            "apply_end_datetime",
            models.mixins.UTCToJSTType(),
            nullable=True,
            comment="適用終了日時",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("work_technologies")
    op.drop_table("skills")
    op.drop_table("project_technologies")
    op.drop_table("work_processes")
    op.drop_table("technologies")
    op.drop_table("background_events")
    op.drop_table("works")
    op.drop_table("technology_categories")
    op.drop_table("skill_categories")
    op.drop_table("projects")
    op.drop_table("profiles")
    op.drop_table("processes")
    op.drop_table("levels")
    op.drop_table("background_eras")
    # ### end Alembic commands ###
